// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCah4nVv9ETqJsyZ0BYIVUUu3S2lz8pvD0',
    appId: '1:360154272752:web:36ccf19b0d3f152cd10335',
    messagingSenderId: '360154272752',
    projectId: 'belajar-78f13',
    authDomain: 'belajar-78f13.firebaseapp.com',
    databaseURL: 'https://belajar-78f13.firebaseio.com',
    storageBucket: 'belajar-78f13.appspot.com',
    measurementId: 'G-2EE9LMYMLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8oq8NIn4u7D9EfRhpvZJoEgp7sUKeAkI',
    appId: '1:360154272752:android:76169af75d59c765d10335',
    messagingSenderId: '360154272752',
    projectId: 'belajar-78f13',
    databaseURL: 'https://belajar-78f13.firebaseio.com',
    storageBucket: 'belajar-78f13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfT1InXOr0KZ9fBISYgiPnl0BzPqALNo',
    appId: '1:360154272752:ios:7f956f0f2e4d7633d10335',
    messagingSenderId: '360154272752',
    projectId: 'belajar-78f13',
    databaseURL: 'https://belajar-78f13.firebaseio.com',
    storageBucket: 'belajar-78f13.appspot.com',
    iosBundleId: 'com.example.motionFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFfT1InXOr0KZ9fBISYgiPnl0BzPqALNo',
    appId: '1:360154272752:ios:ba0d1224cb880315d10335',
    messagingSenderId: '360154272752',
    projectId: 'belajar-78f13',
    databaseURL: 'https://belajar-78f13.firebaseio.com',
    storageBucket: 'belajar-78f13.appspot.com',
    iosBundleId: 'com.example.motionFlutterFirebase.RunnerTests',
  );
}
